### ISSUE TITLE
[Time] TimeTable Modal 추가기능

### ISSUE THREAD

**Issue by SWARVY** [KGU-C-Lab/clab-platforms#213]
### Describe

타임테이블 모달에 아직 구현되지 않은 나머지 기능들을 구현합니다.

### Tasks

- [x] 강의 리스트 무한스크롤 적용
- [x] 반응형 레이아웃 적용
- [x] 디자인 일부 변경
- [x] 강의 선택 시 파라미터에 해당 내용 반영
