### ISSUE TITLE
[Member] 활동 API 연동

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab-platforms#39]
### Describe

동아리원들이 참여하는 스터디나 프로젝트와 관련된 활동 페이지 API를 연동합니다.

### Tasks

- [x] 활동 리스트 조회
- [x] 활동 신청
- [x] 상세 조회
- [x] 공지사항 조회
- [x] 주차 활동 조회
- [x] 참여자 목록
- [x] 과제 조회
- [x] 과제 제출
- [x] 과제 제출 수정
- [x] 과제 피드백 열람
- [x] 신청자 조회 / 수락 / 거절
- [x] 피드백 제출
- [x] 피드백 수정
- [x] 그룹 관리 (리더)
- [x] 새로운 그룹 만들기
- [x] 내가 지원한 그룹 상태
- [x] 그룹 관리 (운영진)

### ETC

출석 관련 시스템은 1.1에서 개발하도록 하겠습니다.
- #61

**Comment by gwansikk** [comment]
@Jeong-Ag 활동 페이지, 작업 현황 여기 이슈에서 공유 부탁드려요

**Comment by gwansikk** [comment]
@Jeong-Ag 해당 이슈 작업 모두 완료된 건가요?? 작업 현황 공유 부탁드려요

**Comment by Jeong-Ag** [comment]
> @Jeong-Ag 해당 이슈 작업 모두 완료된 건가요?? 작업 현황 공유 부탁드려요

이슈 수정 하였습니다 :) 피드백 제출과 피드백 수정도 구현 되었으나 수정된 api 배포 후 확인하여 커밋하도록 하겠습니다. 지원한 그룹 상태와 그룹 관리는 이번주 중으로 완료하여 PR 할 예정입니다.

**Comment by gwansikk** [comment]
> > @Jeong-Ag 해당 이슈 작업 모두 완료된 건가요?? 작업 현황 공유 부탁드려요
> 
> 이슈 수정 하였습니다 :) 피드백 제출과 피드백 수정도 구현 되었으나 수정된 api 배포 후 확인하여 커밋하도록 하겠습니다. 지원한 그룹 상태와 그룹 관리는 이번주 중으로 완료하여 PR 할 예정입니다.

bb 다음 PR에서 현호님이 피드백 주신거 확인 후 개선사항이 있다면 포함하여 올려주세요~

- https://github.com/KGU-C-Lab/clab-platforms/pull/192#pullrequestreview-2229152507
